services:
  # 1. PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: crash_response_db
    restart: always
    environment:
      POSTGRES_DB: vehicle_safety_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muskan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      crash_network:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vehicle_safety_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Spring Boot Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crash_response_backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicle_safety_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: muskan
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      FAST2SMS_API_KEY: "jZou6yaHmD2JsWcbn3K4ESB8OtYd0p1CRfrwVzQl5TvekFXgLiEI0LZWOfsg6QobD9NqaUR3lYnxhP2B"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crash_network

volumes:
  postgres_data:

networks:
  crash_network:
    driver: bridge